{% set name = "richvalues" %}
{% set version = "3.0.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9a6807c09b1be97e07b83eb31262500f3ef271c95a233ac103834cdb2ef5120b

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  description: "README.md"
  doc_url: "https://github.com/andresmegias/richvalues/blob/main/userguide.pdf"

extra:
  recipe-maintainers:
    - andresmegias
