{% set name = "richvalues" %}
{% set version = "4.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8a4b10df89aba4fe74f030ef5d0073debac068b1da32092ed7e18daad3e77458

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  doc_url: "https://github.com/andresmegias/richvalues/blob/main/userguide.pdf"
  description: "RichValues is a Python 3 library for working with numeric values with uncertainties, upper/lower limits and finite intervals, which may be called _rich values_. A user guide and a quick tutorial are available on GitHub: [https://github.com/andresmegias/richvalues/](https://github.com/andresmegias/richvalues/)."

extra:
  recipe-maintainers:
    - andresmegias
