{% set name = "richvalues" %}
{% set version = "4.2.24" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 192dc558d1e346c0dd6dc50538bf15458d13b9837e77a76577e0c2a0ac7ae2ec

build:
  number: 0
  noarch: python

requirements:
  host:
    - python>3.10
    - setuptools
    - pip
  run:
    - python>3.10
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python package for working with uncertainties and upper/lower limits"
  doc_url: "https://github.com/andresmegias/richvalues/blob/main/userguide.pdf"
  description: "RichValues is a Python 3 package for working with numeric values with uncertainties, upper/lower limits and finite intervals, which may be called _rich values_. A user guide and a quick tutorial are available on GitHub: [https://github.com/andresmegias/richvalues/](https://github.com/andresmegias/richvalues/)."

extra:
  recipe-maintainers:
    - andresmegias
