{% set name = "richvalues" %}
{% set version = "3.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 26156e7126b0f0f621fbf8540685b37547548f1f7efd559c5342a41505a502fe

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  doc_url: "https://github.com/andresmegias/richvalues/blob/main/userguide.pdf"
  description: "RichValues is a Python 3 library for working with numeric values with uncertainties, upper/lower limits and finite intervals, which may be called _rich values_. With it, one can import rich values written in plain text documents in an easily readable format, operate with them propagating the uncertainties automatically, and export them in the same formatting style as the import. It also allows to easily plot rich values and to make fits to any function, taking into account the uncertainties and the upper/limits or finite intervals. Moreover, correlations between variables are taken into account when performing calculations with rich values. An user guide is available on the GitHub repository: [https://github.com/andresmegias/richvalues/](https://github.com/andresmegias/richvalues/)."

extra:
  recipe-maintainers:
    - andresmegias
