package:
    name: 'richvalues'
    version: '1.0.5'

source:
    git_rev: v1.0.5
    git_url: https://github.com/andresmegias/richvalues
    
requirements:
    host:
    - python
    - setuptools
    build:
    - python
    run:
    - python
    - numpy
    - pandas
    - jupyter
    - ipykernel

about:
    home: https://github.com/andresmegias/richvalues
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Python library for dealing with uncertainties and upper/lower limits'
