{% set name = "richvalues" %}
{% set version = "1.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9fbdefb52c3068c83abbbf2faafbeb04cd3ebc24d141832798a2736d359c533c

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - andresmegias
