{% set name = "richvalues" %}
{% set version = "3.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d86448a2e19ab073fc4fad00d971fca3d05950f9cb0113664d8212b39288a832

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - andresmegias
