{% set name = "richvalues" %}
{% set version = "3.0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 08c64ca7a274b7f391cff27a973cd8cd47cb384bcfb34a6e7cb80f9bbb505d54

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - matplotlib

about:
  home: "https://github.com/andresmegias/richvalues"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for working with uncertainties and upper/lower limits"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - andresmegias
